# Generated by Django 4.0.6 on 2022-07-13 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registrationprofile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfileModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='registration_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(default=registrationprofile.models.code_generator, max_length=6)),
            ],
        ),
    ]
