# Generated by Django 4.0.6 on 2022-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_initial'),
        ('column', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='columns', to='item.itemmodel'),
        ),
    ]
