# Generated by Django 4.0.6 on 2022-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_initial'),
        ('column', '0004_alter_columnmodel_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmodel',
            name='items',
            field=models.ManyToManyField(blank=True, to='item.itemmodel'),
        ),
    ]
