# Generated by Django 4.0.6 on 2022-07-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_itemmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
