# Generated by Django 4.0.6 on 2022-07-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer_profile', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofilemodel',
            name='favourite_items',
            field=models.ManyToManyField(related_name='favourited_by_buyer', to='item.itemmodel'),
        ),
    ]
