# Generated by Django 4.0.5 on 2022-07-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('buyer_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='buyer_profile.buyerprofilemodel')),
                ('item', models.ManyToManyField(related_name='wish_list', to='item.itemmodel')),
            ],
        ),
    ]
