# Generated by Django 4.0.5 on 2022-07-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('wishlist', '0003_remove_wishlistmodel_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='item.itemmodel'),
        ),
    ]
