# Generated by Django 4.0.5 on 2022-07-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wishlist', '0004_wishlistmodel_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistmodel',
            name='buyer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='users.buyerprofilemodel'),
        ),
    ]
