# Generated by Django 4.0.5 on 2022-07-15 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0005_alter_wishlistmodel_buyer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='buyer_profile',
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
