# Generated by Django 4.0.5 on 2022-07-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wishlist', '0006_remove_wishlistmodel_buyer_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlistmodel',
            name='buyer_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='users.buyerprofilemodel'),
        ),
    ]
