# Generated by Django 4.0.5 on 2022-07-15 12:42

from django.db import migrations, models
import django.db.models.deletion
import review.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('item', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='buyer_profile',
            field=models.ForeignKey(blank=True, on_delete=models.SET(review.models.get_sentinel_user), related_name='reviews', to='users.buyerprofilemodel'),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='item.itemmodel'),
        ),
    ]
