# Generated by Django 4.0.6 on 2022-07-12 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99950, 'The entered zip code is invalid.')]),
        ),
    ]
